kubeconfigs:
  - app: gca
    kubeconfig:
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTmpneE9UYzRPRGd3SGhjTk1qSXhNVEV4TWpBeE9EQTRXaGNOTXpJeE1UQTRNakF4T0RBNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTmpneE9UYzRPRGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUbkZDMi96ek9xaXpHTllDelJITFNkSndjMUJrd0ZVUnhEMTlYc1MzUCsKOGVsU3JzRzltT1JZU0ozUUwzUWdSZUp5NG83dlQ2ZmtIb1AvVVFpMFF1Ui9vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTlnQXVRQ0UvVnBaWTI0eExSNGNiCnlobVcwMzB3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUw2TUtmQ2RWLzhZclhQczIvQTJtY3BmUER0d1RaT0gKTEtudERTR2YwWVQ4QWlFQTRmQUZ5UG8wSjJLOTBKZDZqSnNBTWJ3MFNYTG5oL09yYzZQTGNsM3Ztbk09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          server: https://127.0.0.1:6443
        name: rancher-desktop
      contexts:
      - context:
          cluster: rancher-desktop
          user: gines
        name: gines-rancher-desktop
      current-context: gines-rancher-desktop
      kind: Config
      preferences: {}
      users:
      - name: gines
        user:
          client-certificate: /Users/ginescolladonavarro/proyectos/kubernetes/guia_practica/kbp-sample/certificados/client.crt
          client-key: /Users/ginescolladonavarro/proyectos/kubernetes/guia_practica/kbp-sample/certificados/client-key.pem
  - app: gca
    kubeconfig:
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTmpneE9UYzRPRGd3SGhjTk1qSXhNVEV4TWpBeE9EQTRXaGNOTXpJeE1UQTRNakF4T0RBNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTmpneE9UYzRPRGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUbkZDMi96ek9xaXpHTllDelJITFNkSndjMUJrd0ZVUnhEMTlYc1MzUCsKOGVsU3JzRzltT1JZU0ozUUwzUWdSZUp5NG83dlQ2ZmtIb1AvVVFpMFF1Ui9vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTlnQXVRQ0UvVnBaWTI0eExSNGNiCnlobVcwMzB3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUw2TUtmQ2RWLzhZclhQczIvQTJtY3BmUER0d1RaT0gKTEtudERTR2YwWVQ4QWlFQTRmQUZ5UG8wSjJLOTBKZDZqSnNBTWJ3MFNYTG5oL09yYzZQTGNsM3Ztbk09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          server: https://127.0.0.1:6443
        name: rancher-desktop
      contexts:
      - context:
          cluster: rancher-desktop
          user: gines
        name: gines-rancher-desktop
      current-context: gines-rancher-desktop
      kind: Config
      preferences: {}
      users:
      - name: gines
        user:
          client-certificate: /Users/ginescolladonavarro/proyectos/kubernetes/guia_practica/kbp-sample/certificados/client.crt
          client-key: /Users/ginescolladonavarro/proyectos/kubernetes/guia_practica/kbp-sample/certificados/client-key.pem
